### ISSUE TITLE
Run the code without GPU

### ISSUE THREAD

**Issue by tienduccao** [valdersoul/GraphBTM#1]
Hi, I tried to run your code without GPU and it asked for GPU.
Any suggestion? Thanks.

```
python pytorch_run.py --start --nogpu
loading biterms
Data Loaded
11258
start training
Traceback (most recent call last):
  File "pytorch_run.py", line 243, in <module>
    train(dataset)
  File "pytorch_run.py", line 157, in train
    biterm = torch.FloatTensor(biterm).float().cuda()
  File "/local/tcao/topic_modeling/GraphBTM/.env/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/local/tcao/topic_modeling/GraphBTM/.env/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

**Comment by valdersoul** [comment]
Hi, sorry that I am not checking whether there is a GPU in the code. You can modify the code where there is a '.cuda()' there and remove them. Sorry for the inconvenience.  Or I may upload a fix, but it may take some more days because these days I am quite busy.

**Comment by tienduccao** [comment]
Thanks.
